modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="andvari"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.andvari]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.andvari]]
modId = "tetra"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"